config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    # Ressources
    resources :gossips do
      resources :comments
      resources :likes, only: %i[create destroy]
    end
    resources :users
    resources :cities, only: %i[show index]
    resources :sessions, only: %i[new create destroy]
  
    # Root
    get root 'gossips#index'
  
    # Landing page
    get 'welcome/:user_name', to: 'welcome#show', as: 'welcome'
  
    # Static pages
    get 'team', to: 'static_pages#team'
    get 'contact', to: 'static_pages#contact'
  
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users, dependent: :destroy # Yes, if city blows up, users from that city die! Hahaha 
  has_many :gossips, through: :users
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: :User, foreign_key: :author_id

  belongs_to :commentable, polymorphic: true
  has_many :comments, as: :commentable, dependent: :destroy

  validates :content, presence: true

  def get_gossip
    if commentable_type == 'Gossip'
      commentable
    else 
      commentable.get_gossip
    end
  end
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :author, class_name: :User, foreign_key: :author_id
  has_many :comments, as: :commentable, dependent: :destroy

  has_many :likes, dependent: :destroy

  validates :title, length: { in: 6..20 }

  validates :content, presence: true

  def liked_by?(user)
    !like_by(user).nil?
  end

  def like_by(user)
    likes.find { |like| like.user_id == user&.id }
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :gossip

  validate :no_duplicate

  private

  def no_duplicate
    return unless user && gossip

    errors.add(:user_id, 'Already liked') if gossip.liked_by?(user)
  end
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :city
  has_many :gossips, foreign_key: :author_id, dependent: :destroy
  has_many :comments, foreign_key: :author_id, dependent: :destroy

  has_many :likes, dependent: :destroy

  #validates :password, presence: true, length: { minimum: 6 }

  validates :email,
            presence: true,
            uniqueness: true,
            format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: 'email address please' }

  validates :first_name, length: { minimum: 2 }
  validates :last_name, length: { minimum: 2 }

  has_secure_password

  def full_name
    "#{first_name} #{last_name}"
  end

  def remember(remember_token)
    remember_digest = BCrypt::Password.create(remember_token)
    self.update(remember_digest: remember_digest)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper 
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def show
    @city = City.find(params[:id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user, only: %i[new create edit update destroy]

  def new
    @gossip = Gossip.find(params[:gossip_id])
    @comment = Comment.new
  end

  def update
    @comment = Comment.find(params[:id])

    if @comment.update(comment_params)
      redirect_to @comment.get_gossip
    else
      render :edit
    end
  end

  def create
    @gossip = Gossip.find(params[:gossip_id])

    @comment = Comment.new(comment_params)
    @comment.author = current_user
    @comment.commentable = @gossip
    puts @comment

    if @comment.save
      redirect_to @gossip
    else
      render :new
    end
  end

  def edit
    @gossip = Gossip.find(params[:gossip_id])
    @comment = Comment.find(params[:id])
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    redirect_to @comment.get_gossip
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end

  def authenticate_user
    unless current_user
      flash[:danger] = 'Il est nécessaire de se connecter avant de créer un commentaire'
      redirect_to new_session_path
    end
  end
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  before_action :authenticate_user, only: %i[new create edit update destroy]

  def index
    @gossips = Gossip.all
  end

  def show
    @gossip = Gossip.find(params[:id])
  end

  def new
    @gossip = Gossip.new
  end

  def create
    @gossip = Gossip.new(gossip_params)
    @gossip.author = current_user

    if @gossip.save
      redirect_to @gossip
    else
      render :new
    end
  end

  def edit
    @gossip = Gossip.find(params[:id])
  end

  def update
    @gossip = Gossip.find(params[:id])

    if @gossip.update(gossip_params)
      redirect_to @gossip
    else
      render :edit
    end
  end

  def destroy
    @gossip = Gossip.find(params[:id])
    @gossip.destroy

    redirect_to gossips_path
  end

  private

  def gossip_params
    params.require(:gossip).permit(:title, :content)
  end

  def authenticate_user
    unless current_user
      flash[:danger] = 'Il est nécessaire de se connecter avant de créer un potin'
      redirect_to new_session_path
    end
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @gossip = Gossip.find(params[:gossip_id])

    @like = Like.new(gossip: @gossip)
    @like.user = current_user

    if @like.save
      redirect_to request.referrer
    end
  end

  def destroy
    @like = Like.find(params[:id])
    @like.destroy

    redirect_to request.referrer
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by(email: params[:email])

    if user&.authenticate(params[:password])
      log_in(user)
      remember(user) if params[:remember_me]
      redirect_to gossips_path
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render :new
    end
  end

  def destroy
    log_out(current_user)
    redirect_to gossips_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def team
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      log_in(@user)
      remember(@user) if params.require(:user).permit(:remember_me)

      redirect_to gossips_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :age, :city_id, :password, :password_confirmation, :description)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def show
    @user_name = params[:user_name]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    User.find_by(id: session[:user_id])
  end

  def log_in(user)
    session[:user_id] = user.id
 end

  def current_user
    if session[:user_id]
      current_user = User.find_by(id: session[:user_id])
    elsif cookies[:user_id]
      user = User.find_by(id: cookies[:user_id])
      if user && BCrypt::Password.new(user.remember_digest).is_password?(cookies[:remember_token])
        log_in user
        current_user = user
      end
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def remember(user)
    remember_token = SecureRandom.urlsafe_base64
    user.remember(remember_token)
    cookies.permanent[:user_id] = user.id
    cookies.permanent[:remember_token] = remember_token
  end

  def forget(user)

    # on remet le remember_digest à nil puisqu'il ne nous servira plus :
    user.update!(remember_digest: nil)
  
    # on efface les cookies dans le navigateur de l'utilisateur
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  
  end

  def log_out(user)
    session.delete(:user_id)
    forget(user)
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cities/_city.html.erb
<h1> <%= city.name %> </h1>

app/views/cities/show.html.erb
<%= render partial: "shared/header" %>

<div class="container">

  <%= render partial: "cities/city", locals: {city: @city} %>

  <h2 class="mb-4 mt-4"> Utilisateurs (<%= @city.users.size %>) : </h2>

  <%= render partial: "users/list", locals: {users: @city.users} %>

  <h2 class="mb-4 mt-4"> Potins (<%= @city.gossips.size %>) : </h2>

  <%= render partial: "gossips/list", locals: {gossips: @city.gossips} %>

</div>

app/views/comments/_form.html.erb
<%= form_with model: [@gossip, @comment], local: true do |form| %>

<% if @comment.errors.any? %>
<div class="alert alert-warning" role="alert">
  <p>Nous n'avons pas réussi à créer le commentaire pour la (ou les) raison(s) suivante(s) :</p>
  <ul>
    <% @comment.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>
<table>
  <tr>
    <td> <%= form.label 'Contenu' %> </td>
    <td> <%= form.text_area :content,  rows: 5, cols: 80 %> </td>
  </tr>
  <tr>
    <td> </td>
    <td> <%= form.submit "Valider", class: "btn btn-primary" %> </td>
  </tr>
</table>

<% end %>

app/views/comments/_light.html.erb
<li> 
  <%= link_to comment.author.full_name, user_path(comment.author) %> : 
  <%= comment.content %> 
  <% if current_user == comment.author %>
  (<%= link_to "éditer", edit_gossip_comment_path(comment.get_gossip, comment) %>)
  <% end %>
</li>

app/views/comments/_list.html.erb
<% if comments.size > 0 %>
<ul>
  <% comments.each do |comment| %>
  <%= render partial: "comments/light", locals: {comment: comment} %>
  <%= render partial: "comments/list", locals: {comments: comment.comments} %>
  <% end %>
</ul>
<% end %>

app/views/comments/edit.html.erb
<%= render partial: "shared/header" %>

<div class="container">

  <%= render partial: "gossips/gossip", locals: {gossip: @gossip} %>

  <%= render partial: "comments/form", locals: {gossip: @gossip} %>

  <%= link_to gossip_comment_path(@gossip, @comment), data: { confirm: "Confirmer la suppression du commentaire :\n#{@comment.content}", method: :delete} do %>
  <button type="button" class="btn btn-warning"> Supprimer le commentaire </button>
  <% end %>


</div>

app/views/comments/new.html.erb
<%= render partial: "shared/header" %>

<div class="container">

  <%= render partial: "gossips/gossip", locals: {gossip: @gossip} %>

  <%= render partial: "comments/form", locals: {gossip: @gossip} %>

</div>

app/views/gossips/_form.html.erb
<%= form_with model: @gossip, local: true do |form| %>

<% if @gossip.errors.any? %>
<div class="alert alert-warning" role="alert">
  <p>Nous n'avons pas réussi à créer le potin pour la (ou les) raison(s) suivante(s) :</p>
  <ul>
    <% @gossip.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>
<table>
  <tr>
    <td> <%= form.label 'Titre' %> </td>
    <td> <%= form.text_field :title, size: 80 %> </td>
  </tr>
  <tr>
    <td> <%= form.label 'Contenu' %> </td>
    <td> <%= form.text_area :content,  rows: 5, cols: 80 %> </td>
  </tr>
  <tr>
    <td> </td>
    <td> <%= form.submit "Valider", class: "btn btn-primary" %> </td>
  </tr>
</table>

<% end %>

app/views/gossips/_gossip.html.erb
<div class="card border-primary mb-3">
  <div class="card-header text-primary">
    <div class="d-flex w-100 justify-content-between">
      <h4 class="mb-1"> <%= gossip.title %> </h5>
      <%= render partial: 'likes/like', locals: {gossip: gossip} %>
    </div>
    </div>
  <div class="card-body">
    <p class="card-text">
      <% gossip.content.split("\n").each do |line| %>
      <%= line %> <br />
      <% end %>

    </p>
  </div>
  <%= link_to user_path(gossip.author.id), :action => 'go' do %>
  <div class="card-body text-primary"> Auteur : <%= gossip.author.first_name %> <%= gossip.author.last_name %>  il y a <%= TimeDifference.between(Time.now, gossip.updated_at).humanize %> </div>
  <% end %>
  <%= link_to city_path(gossip.author.city.id), :action => 'go' do %>
  <div class="card-body text-info"> Vile : <%= gossip.author.city.name %> </div>
  <% end %>
</div>
<% if current_user == gossip.author %>
<%= link_to edit_gossip_path(gossip) do %>
<button type="button" class="btn btn-secondary"> Editer le potin </button>
<% end %>

<%= link_to gossip_path(gossip), data: { confirm: "Confirmer la suppression du potin :\n#{gossip.title}", method: :delete} do %>
<button type="button" class="btn btn-warning"> Supprimer le potin </button>
<% end %>
<% end %>

<div class="card border-secondary mb-3 mt-4">
  <div class="card-body">
    <h5 class="card-text"> Commentaires </h5>
    <%= render partial: "comments/list", locals: {comments: gossip.comments.sort_by(&:created_at)} %>
  </div>
</div>

<%= link_to new_gossip_comment_path(gossip), :action => 'go' do %>
<button type="button" class="btn btn-primary"> Ajouter un commentaire ! </button>
<% end %>

app/views/gossips/_light.html.erb
<div class="list-group-item list-group-item-action">
  <%= link_to gossip_path(gossip.id), :action => 'go' do %>
  <h5 class="d-flex w-100 pb-1"> <%= gossip.title %> </h5>
  <% end %>
  <div class="d-flex w-100 justify-content-between">
    <small> <%= gossip.author.first_name %> <%= gossip.author.last_name %> (<%= gossip.comments.size %>
      commentaires) <%= TimeDifference.between(Time.now, gossip.updated_at).humanize %> </small>
      <small> <%= render partial: 'likes/like', locals: {gossip: gossip} %> </small>
    </div>
  </div>

app/views/gossips/_list.html.erb
<div class="list-group">
  <%= render partial: 'gossips/light', collection: gossips, as: :gossip %>
</div>

app/views/gossips/edit.html.erb
<%= render partial: "shared/header" %>

<div class="container">

  <div class="card border-primary mb-3">
    <div class="card-header text-primary">
      Modifie le potin </div>
    <div class="card-body">
      <%= render partial: "gossips/form" %>
    </div>
  </div>
</div>

app/views/gossips/index.html.erb
<%= render partial: "shared/header" %>

<div class="container">

  <h1 class="mb-4"> Bienvenue sur The Gossip Project ! </h1>

  <%= link_to new_gossip_path, :action => 'go' do %>
  <button type="button" class="btn btn-primary"> Créer un potin ! </button>
  <% end %>


  <h2 class="mb-4 mt-4"> Voici la liste de tous les potins (<%= @gossips.size %>)</h2>

  <%= render partial: "gossips/list", locals: {gossips: @gossips.sort_by(&:created_at).reverse} %>

</div>

app/views/gossips/new.html.erb
<%= render partial: "shared/header" %>

<div class="container">

  <div class="card border-primary mb-3">
    <div class="card-header text-primary">
      Créé un nouveau potin (anonyme) </div>
    <div class="card-body">
      <%= render partial: "gossips/form" %>
    </div>
  </div>
</div>

app/views/gossips/show.html.erb
<%= render partial: "shared/header" %>

<div class="container">

    <%= render partial: "gossips/gossip", locals: {gossip: @gossip} %>

</div>

app/views/likes/_like.html.erb
<span>
  <%= gossip.likes.size %> likes

  <% if logged_in? %>
  <% if gossip.liked_by?(current_user) %>

  <%= link_to "UNLIKE", gossip_like_path(gossip.id, gossip.like_by(current_user)), method: :delete, class: "btn btn-outline-secondary btn-sm" %>

  <% else %>

  <%= link_to "LIKE", gossip_likes_path(gossip.id), method: :post, class: "btn btn-outline-success btn-sm" %>

  <% end %>
  <% end %>
</span>

app/views/users/_form.html.erb
<%= form_with model: @user, local: true do |form| %>

<% if @user.errors.any? %>
<div class="alert alert-warning" role="alert">
  <p>Nous n'avons pas réussi à créer l'utilisateur pour la (ou les) raison(s) suivante(s) :</p>
  <ul>
    <% @user.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>
<table>
  <tr>
    <td> <%= form.label 'Prénom' %> </td>
    <td> <%= form.text_field :first_name, size: 80 %> </td>
  </tr>
  <tr>
    <td> <%= form.label 'Nom' %> </td>
    <td> <%= form.text_field :last_name, size: 80 %> </td>
  </tr>
  <tr>
    <td> <%= form.label 'Email' %> </td>
    <td> <%= form.email_field :email, size: 80 %> </td>
  </tr>
  <tr>
    <td> <%= form.label 'Description' %> </td>
    <td> <%= form.text_area :description,  rows: 5, cols: 80 %> </td>
  </tr>
  <tr>
    <td> <%= form.label 'Age' %> </td>
    <td> <%= form.number_field :age, {value: '99', min: 13, max: 99 } %> </td>
  </tr>
  <tr>
    <td> <%= form.label 'Ville' %> </td>
    <td> <%= form.select(:city_id, City.all.map {|c| [c.name, c.id]}) %> </td>
  </tr>
  <tr>
    <td> <%= form.label 'Mot de passe' %> </td>
    <td> <%= form.password_field :password %> </td>
  </tr>
  <tr>
    <td> <%= form.label 'Confirmation' %> </td>
    <td> <%= form.password_field :password_confirmation %> </td>
  </tr>
  <tr>
    <td>  </td>
    <td> <%= form.check_box :remember_me %> Garder la session ouverte </td>
  </tr>
  <tr>
    <td> </td>
    <td> <%= form.submit "Valider", class: "btn btn-primary" %> </td>
  </tr>
</table>

<% end %>

app/views/users/_light.html.erb
<%= link_to user_path(user.id), :action => 'go' do %>
<div class="list-group-item list-group-item-action">
  <div class="d-flex w-100 justify-content-between">
    <h5 class="mb-1"> <%= user.first_name %> <%= user.last_name %> </h5>
    <small> <%= user.gossips.size %> potins </small>
  </div>
</div>
<% end %>

app/views/users/_list.html.erb
<div class="list-group">
  <%= render partial: 'users/light', collection: users, as: :user %>
</div>

app/views/users/_user.html.erb
<div class="card border-primary mb-3">
  <div class="card-header text-primary">
    <h4> <%= user.first_name %> <%= user.last_name %> </h4>
  </div>
  <div class="card-body">
    <p class="card-text"> <%= user.description %> <br>
      <small class="text-muted"> <%= user.email %> (<%= user.age %> ans)</small></p>
  </div>
  <%= link_to city_path(user.city.id), :action => 'go' do %>
  <div class="card-footer text-primary"> Vile : <%= user.city.name %> </div>
  <% end %>
</div>

app/views/users/new.html.erb
<%= render partial: "shared/header" %>

<div class="container">

  <div class="card border-primary mb-3">
    <div class="card-header text-primary">
      Créé ton compte utilisateur 
    </div>
    <div class="card-body">
      <%= render partial: "users/form" %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<%= render partial: "shared/header" %>

<div class="container">

  <%= render partial: "users/user", locals: {user: @user} %>

  <h2 class="mb-4 mt-4"> Potins (<%= @user.gossips.size %>) : </h2>

  <%= render partial: "gossips/list", locals: {gossips: @user.gossips} %>

</div>