config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    # Ressources
    resources :gossips do
      resources :comments
      resources :likes, only: %i[create destroy]
    end
    resources :users
    resources :cities, only: %i[show index]
    resources :sessions, only: %i[new create destroy]
  
    # Root
    get root 'gossips#index'
  
    # Landing page
    get 'welcome/:user_name', to: 'welcome#show', as: 'welcome'
  
    # Static pages
    get 'team', to: 'static_pages#team'
    get 'contact', to: 'static_pages#contact'
  
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users, dependent: :destroy # Yes, if city blows up, users from that city die! Hahaha 
  has_many :gossips, through: :users
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: :User, foreign_key: :author_id

  belongs_to :commentable, polymorphic: true
  has_many :comments, as: :commentable, dependent: :destroy

  validates :content, presence: true

  def get_gossip
    if commentable_type == 'Gossip'
      commentable
    else 
      commentable.get_gossip
    end
  end
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :author, class_name: :User, foreign_key: :author_id
  has_many :comments, as: :commentable, dependent: :destroy

  has_many :likes, dependent: :destroy

  validates :title, length: { in: 6..20 }

  validates :content, presence: true

  def liked_by?(user)
    !like_by(user).nil?
  end

  def like_by(user)
    likes.find { |like| like.user_id == user&.id }
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :gossip

  validate :no_duplicate

  private

  def no_duplicate
    return unless user && gossip

    errors.add(:user_id, 'Already liked') if gossip.liked_by?(user)
  end
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :city
  has_many :gossips, foreign_key: :author_id, dependent: :destroy
  has_many :comments, foreign_key: :author_id, dependent: :destroy

  has_many :likes, dependent: :destroy

  #validates :password, presence: true, length: { minimum: 6 }

  validates :email,
            presence: true,
            uniqueness: true,
            format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: 'email address please' }

  validates :first_name, length: { minimum: 2 }
  validates :last_name, length: { minimum: 2 }

  has_secure_password

  def full_name
    "#{first_name} #{last_name}"
  end

  def remember(remember_token)
    remember_digest = BCrypt::Password.create(remember_token)
    self.update(remember_digest: remember_digest)
  end
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def show
    @city = City.find(params[:id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user, only: %i[new create edit update destroy]

  def new
    @gossip = Gossip.find(params[:gossip_id])
    @comment = Comment.new
  end

  def update
    @comment = Comment.find(params[:id])

    if @comment.update(comment_params)
      redirect_to @comment.get_gossip
    else
      render :edit
    end
  end

  def create
    @gossip = Gossip.find(params[:gossip_id])

    @comment = Comment.new(comment_params)
    @comment.author = current_user
    @comment.commentable = @gossip
    puts @comment

    if @comment.save
      redirect_to @gossip
    else
      render :new
    end
  end

  def edit
    @gossip = Gossip.find(params[:gossip_id])
    @comment = Comment.find(params[:id])
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    redirect_to @comment.get_gossip
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end

  def authenticate_user
    unless current_user
      flash[:danger] = 'Il est nécessaire de se connecter avant de créer un commentaire'
      redirect_to new_session_path
    end
  end
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  before_action :authenticate_user, only: %i[new create edit update destroy]

  def index
    @gossips = Gossip.all
  end

  def show
    @gossip = Gossip.find(params[:id])
  end

  def new
    @gossip = Gossip.new
  end

  def create
    @gossip = Gossip.new(gossip_params)
    @gossip.author = current_user

    if @gossip.save
      redirect_to @gossip
    else
      render :new
    end
  end

  def edit
    @gossip = Gossip.find(params[:id])
  end

  def update
    @gossip = Gossip.find(params[:id])

    if @gossip.update(gossip_params)
      redirect_to @gossip
    else
      render :edit
    end
  end

  def destroy
    @gossip = Gossip.find(params[:id])
    @gossip.destroy

    redirect_to gossips_path
  end

  private

  def gossip_params
    params.require(:gossip).permit(:title, :content)
  end

  def authenticate_user
    unless current_user
      flash[:danger] = 'Il est nécessaire de se connecter avant de créer un potin'
      redirect_to new_session_path
    end
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @gossip = Gossip.find(params[:gossip_id])

    @like = Like.new(gossip: @gossip)
    @like.user = current_user

    if @like.save
      redirect_to request.referrer
    end
  end

  def destroy
    @like = Like.find(params[:id])
    @like.destroy

    redirect_to request.referrer
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      log_in(@user)
      remember(@user) if params.require(:user).permit(:remember_me)

      redirect_to gossips_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :age, :city_id, :password, :password_confirmation, :description)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def show
    @user_name = params[:user_name]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    User.find_by(id: session[:user_id])
  end

  def log_in(user)
    session[:user_id] = user.id
 end

  def current_user
    if session[:user_id]
      current_user = User.find_by(id: session[:user_id])
    elsif cookies[:user_id]
      user = User.find_by(id: cookies[:user_id])
      if user && BCrypt::Password.new(user.remember_digest).is_password?(cookies[:remember_token])
        log_in user
        current_user = user
      end
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def remember(user)
    remember_token = SecureRandom.urlsafe_base64
    user.remember(remember_token)
    cookies.permanent[:user_id] = user.id
    cookies.permanent[:remember_token] = remember_token
  end

  def forget(user)

    # on remet le remember_digest à nil puisqu'il ne nous servira plus :
    user.update!(remember_digest: nil)
  
    # on efface les cookies dans le navigateur de l'utilisateur
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  
  end

  def log_out(user)
    session.delete(:user_id)
    forget(user)
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheGossipProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "The Gossip Project ❤️", root_path, :class => "nav-link" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">

    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Home", root_path, :class => "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Team", team_path, :class => "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Contact", contact_path, :class => "nav-link" %>
      </li>
      <li></li>

      <% if logged_in? %>
      <li class="nav-item ml-2">
        <%= link_to "Se déconnecter", session_path(session.id), method: :delete, :class => "nav-link btn btn-secondary text-white  btn-sm" %>
      </li>
      <li class="nav-item ml-2">
        <%= link_to current_user.full_name, user_path(current_user.id), :class => "nav-link" %>
      </li>
      <% else %>
      <li class="nav-item ml-2">
        <%= link_to "Se connecter", new_session_path, :class => "nav-link btn btn-primary text-white  btn-sm" %>
      </li>
      <li class="nav-item ml-2">
        <%= link_to "Créer un compte", new_user_path, :class => "nav-link btn btn-success text-white  btn-sm" %>
      </li>
      <% end %>
    </ul>

  </div>
</nav>